Dev link open file
baza-trainee/ataka-help-front-end pull request #17
Opened 2023-05-18 17:34 UTC by KonstantinLigus

Підключив pdf.js reader - відображає на всіх екранах

2023-05-18 20:25 UTC, I-Kolesnyk approved these changes

2023-05-18 20:31 UTC, I-Kolesnyk requested changes

2023-05-18 20:31 UTC, I-Kolesnyk commented on src/components/Modal/Modal.tsx
> +    const pressEscCloseModalHandler = (event: any) => {
у івента є свій спеціальний тип, наприклад,  React.MouseEvent<HTMLButtonElement>

2023-05-19 07:26 UTC, KonstantinLigus commented on src/components/Modal/Modal.tsx
> +    const pressEscCloseModalHandler = (event: any) => {
Добре, додам

2023-05-20 10:31 UTC, Lysak-Anna commented on src/components/Modal/Modal.styled.tsx
> +  border-top: solid ${theme.colors.white[100]} 16px;
Подивись, будь-ласка, наші загальні правила, які я написала, як ми використовуємо тему в стилях. Для однорідності коду, ми її не імпортуємо, а дістаємо з пропсів

2023-05-20 10:51 UTC, Lysak-Anna commented on src/components/FileOpenLink/FileOpenLink.tsx
>        <span onClick={clickTextHandler}>{text}</span>
це, мабуть, має бути button

2023-05-23 18:58 UTC, baza-trainee approved these changes

2023-05-23 18:59 UTC, I-Kolesnyk approved these changes

2023-05-23 18:59 UTC, merged