Feature/nav link add props
baza-trainee/ataka-help-front-end pull request #18
Opened 2023-05-22 11:24 UTC by kovalevaMarina

2023-05-22 12:20 UTC, baza-trainee requested changes

2023-05-22 12:20 UTC, baza-trainee commented on src/components/NavLink/NavLink.styled.tsx
> +interface LinkProps {
перенеси усі інтерфейси у папку types в окремі файли

2023-05-22 12:20 UTC, baza-trainee commented on src/components/NavLink/NavLink.styled.tsx
> +  children: string;
children - це не стрінга, це ReactNode (import { ReactNode } from "react";)

2023-05-22 15:17 UTC, Lysak-Anna commented on src/components/NavLink/NavLink.styled.tsx
> +import { Theme } from "@emotion/react";
Імпорт теми з емошн не потрібен, у нас своя тема, вона в стилях доступна без імпорту

2023-05-22 16:54 UTC, baza-trainee commented on src/components/NavLink/NavLink.tsx
> +        {children}
children - це зарезервоване слово, дай іншу назву пропсу

2023-05-22 18:17 UTC, kovalevaMarina commented on .vscode/settings.json
> +}
вже додала

2023-05-23 10:31 UTC, baza-trainee approved these changes

2023-05-23 10:32 UTC, merged