add adaptive styles, add logic to analytics
baza-trainee/ataka-help-front-end pull request #50
Opened 2023-05-25 16:04 UTC by VitaliiVeshtobei

2023-05-25 19:32 UTC, I-Kolesnyk requested changes

2023-05-25 19:32 UTC, I-Kolesnyk commented on src/components/CookieConsentBanner/CookieConsentBanner.tsx
>                <a href="">Політика конфіденційності</a>
це має бути компонент FileOpenLink, якому передається три пропси text, path, isTextUnderline

2023-05-25 19:32 UTC, I-Kolesnyk commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
>      & a {
прибрати, стилізація вже буде на компоненті

2023-05-25 19:32 UTC, I-Kolesnyk commented on src/components/FeedbackForm/FeedbackForm.tsx
> -
це не твій файл, прибери зміни

2023-05-25 22:42 UTC, Lysak-Anna commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
> +import { theme } from "@/theme";
Тема у стилях доступна без імпорту

2023-05-25 22:43 UTC, Lysak-Anna commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
>    color: ${p => p.theme.colors.white[100]};
Зроби, будь-ласка, деструктуризацію теми, щоб однаково було

2023-05-25 22:46 UTC, Lysak-Anna commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
> +    line-height: 19.5px;
Забери усюди line-height, він прописаний у глобальних стилях

2023-05-26 08:18 UTC, VitaliiVeshtobei commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
>    & h3 {
Зробив окремими компонентами

2023-05-26 08:29 UTC, VitaliiVeshtobei commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
>      & a {
прибрав

2023-05-26 08:29 UTC, VitaliiVeshtobei commented on src/components/FeedbackForm/FeedbackForm.tsx
> -
це зробив форматер, я туди не ліз

2023-05-26 08:29 UTC, VitaliiVeshtobei commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
> +import { theme } from "@/theme";
видалив

2023-05-26 08:35 UTC, VitaliiVeshtobei commented on src/components/CookieConsentBanner/CookieConsentBanner.styled.ts
> +    line-height: 19.5px;
зробив

2023-05-26 09:13 UTC, I-Kolesnyk approved these changes

2023-05-26 09:18 UTC, Lysak-Anna approved these changes

2023-05-26 09:45 UTC, merged