Feature/file open link
baza-trainee/ataka-help-front-end pull request #60
Opened 2023-05-26 19:28 UTC by KonstantinLigus

Додав стилізацію для cookies - з'явились нові пропси: isFooterButtonStyles, isCookiesButtonStyles

2023-05-26 21:37 UTC, I-Kolesnyk approved these changes

2023-05-27 09:59 UTC, I-Kolesnyk requested changes

2023-05-27 09:59 UTC, I-Kolesnyk commented on src/components/FileOpenLink/FileOpenLink.styled.tsx
> +interface IStyles {
перенести в папку types

2023-05-27 12:37 UTC, Lysak-Anna approved these changes

2023-05-28 15:06 UTC, KonstantinLigus commented on src/components/FileOpenLink/FileOpenLink.styled.tsx
> +interface IStyles {
вже переніс

2023-05-29 14:32 UTC, KonstantinLigus commented
повернув стан як для одного pdf файлу

2023-05-29 14:34 UTC, Lysak-Anna approved these changes

2023-05-29 15:32 UTC, I-Kolesnyk approved these changes

2023-05-29 15:32 UTC, merged